import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {parseStepRelease,StepcodeRuntimeUpdater} from '../src/main/stepcodeRuntimeUpdater.ts';
const manifest={version:'0.1.2',packages:{'windows-x64':'https://static-openapi.stepfun.com/stepcode/0.1.2/step.zip'},checksums:{'windows-x64':'a'.repeat(64)}};
test('update: newer official Windows release only; no downgrade or foreign origin',()=>{assert.equal(parseStepRelease(manifest,'0.1.0','x64')?.version,'0.1.2');assert.equal(parseStepRelease(manifest,'0.1.2','x64'),null);assert.equal(parseStepRelease(manifest,'1.0.0','x64'),null);assert.throws(()=>parseStepRelease({...manifest,packages:{'windows-x64':'https://example.com/x.zip'}},'0.1.0','x64'));});
test('update: bad checksum never switches active runtime',async()=>{const root=await mkdtemp(join(tmpdir(),'step-update-'));try{const states=[];const updater=new StepcodeRuntimeUpdater(root,'0.1.0',s=>states.push(s),()=>{},async url=>String(url).endsWith('latest.json')?Response.json(manifest):new Response('corrupt'));await updater.check();await assert.rejects(updater.download(),/校验失败/);await assert.rejects(readFile(join(root,'current.json')),/ENOENT/);assert.equal(states.at(-1).kind,'update-available');}finally{await rm(root,{recursive:true,force:true});}});

test('manual update: current version reports latest and restores enabled state',async()=>{const states=[];const updater=new StepcodeRuntimeUpdater('unused','0.1.2',s=>states.push(s),()=>{},async()=>Response.json(manifest));assert.deepEqual(await updater.check({manual:true}),{kind:'up-to-date',currentVersion:'0.1.2'});assert.deepEqual(states.map(s=>s.kind),['checking','idle']);assert.equal(states.at(-1).enabled,true);});

test('manual update: returns runtime release notes and restores skipped release',async()=>{const updater=new StepcodeRuntimeUpdater('unused','0.1.0',()=>{},()=>{},async()=>Response.json(manifest));assert.equal((await updater.check()).kind,'available');updater.skip('0.1.2');assert.equal((await updater.check()).kind,'up-to-date');const result=await updater.check({manual:true});assert.equal(result.kind,'available');assert.equal(result.releaseNotes?.title,'StepCode 底座 0.1.2');assert.match(result.releaseNotes?.markdown||'',/桌面界面、会话和 API 配置保持不变/);});

test('manual update: failed check is not latest and can be retried',async()=>{let calls=0;const states=[];const updater=new StepcodeRuntimeUpdater('unused','0.1.2',s=>states.push(s),()=>{},async()=>++calls===1?new Response('',{status:503}):Response.json(manifest));await assert.rejects(updater.check({manual:true}),/HTTP 503/);assert.deepEqual(states.at(-1),{kind:'idle',enabled:true});assert.equal((await updater.check({manual:true})).kind,'up-to-date');assert.equal(calls,2);});

test('manual update: concurrent checks reuse one manifest request',async()=>{let resolveResponse;let calls=0;const updater=new StepcodeRuntimeUpdater('unused','0.1.2',()=>{},()=>{},()=>{calls++;return new Promise(resolve=>{resolveResponse=resolve;});});const one=updater.check(),two=updater.check({manual:true});resolveResponse(Response.json(manifest));assert.deepEqual(await one,await two);assert.equal(calls,1);});

test('manual update: download in progress reports progress without rechecking',async()=>{const root=await mkdtemp(join(tmpdir(),'step-update-'));try{let streamController;let checks=0;const updater=new StepcodeRuntimeUpdater(root,'0.1.0',()=>{},()=>{},async url=>{if(String(url).endsWith('latest.json')){checks++;return Response.json(manifest);}return new Response(new ReadableStream({start(controller){streamController=controller;}}));});await updater.check();const download=updater.download();await Promise.resolve();await Promise.resolve();assert.deepEqual(await updater.check({manual:true}),{kind:'already-downloading',version:'0.1.2',progress:'0%'});assert.equal(checks,1);streamController.enqueue(new TextEncoder().encode('corrupt'));streamController.close();await assert.rejects(download,/校验失败/);}finally{await rm(root,{recursive:true,force:true});}});
